### ISSUE TITLE
Getting Panic - quick question

### ISSUE THREAD

**Issue by dstroot** [tj/go-mail#1]
tj - trying this out.  AWS credentials are in ENV variables.  I think I need to instantiate the ses svc somewhere and that is probably what I am missing right?

```
/**
 * Send email via SES
 */

var sesEmail ses.Email
var s ses.SES

sesEmail.From = fromEmail
sesEmail.To = append(sesEmail.To, email)
sesEmail.Subject = subject
sesEmail.HTML = htmlMessage
sesEmail.Text = textMessage

err := s.SendEmail(sesEmail)
if err != nil {
  log.Println(err)
} else {
  report.Emails++
}
```

getting a panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x1d8 pc=0x1efbe7]

goroutine 38 [running]:
panic(0x5b33c0, 0xc82000a130)
    /usr/local/opt/go/libexec/src/runtime/panic.go:464 +0x3e6
github.com/dstroot/email_machine/vendor/github.com/tj/go-ses.(*SES).SendEmail(0xc820603b18, 0xc8201c7ae0, 0x11, 0xc8203f1220, 0x1, 0x1, 0xc82000bef0, 0x6, 0xc820455980, 0x16a, ...)
    /Users/Dan/Go/src/github.com/dstroot/email_machine/vendor/github.com/tj/go-ses/ses.go:55 +0x487
main.main.func3(0xc8201c8ba0, 0xc82053cf00)
    /Users/Dan/Go/src/github.com/dstroot/email_machine/email_machine.go:380 +0x199c
created by main.main
    /Users/Dan/Go/src/github.com/dstroot/email_machine/email_machine.go:473 +0x3dc
exit status 2
```

**Comment by tj** [comment]
yup it doesn't make any assumptions about creds etc so you have to pass `ses.New(session.New(aws.NewConfig()))` or similar into Service, I should probably add an example haha

**Comment by dstroot** [comment]
Got it - thanks!  Appreciate all the software you've brought to the world.  I'm still a big user of Express.  Cheers!

**Comment by tj** [comment]
np! thanks man
